services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - sample-network
  backend:
    build:
      context: ./backend-py
      dockerfile: Dockerfile
    networks:
      - sample-network

networks:
  sample-network:
    driver: bridge
