services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sample-network
    volumes:
      - ./certs:/etc/nginx/certs:ro
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - sample-network
  backend:
    build:
      context: ./backend-py
      dockerfile: Dockerfile
    networks:
      - sample-network

networks:
  sample-network:
    driver: bridge
